language: node_js

node_js:
  - 10

env:
  global:
    - PATH=$PATH:./node_modules/.bin
    - secure: IU0V0Y57y7dTRnA+Ea/LC7Efx/zznulLsl4qWoH1etm8/l3JzZCiJlXJ8wJk1i6X0gzGLWlkO+710DJyWuajchUP0IfD77LwFVKCazybSnn3tS2r2o/EgUB+iysI1yPyAKomqsFixtVyv+qwGdCjwnmE8NxSC3iSZ1FhBc0/w5dtz5e6ateOHgkcoREl1K87al9UsTljcRQph1LMgkQqv4LlVxDQ9TqpgMRO0nThfgZybvs1MYmI9n/1QzlmOQGHCvsyiY/eUmXy/Dn8LBqRs/fYaOTyqMUEmMCB80TRtgasF702boAHrPkfjbmjD5Ca1uKMYzpMqbXDr8AVXe0yxg==
build:
  # http://docs.shippable.com/ci/shippableyml/#ci
  ci:
    - npm install --no-audit
    - npm run lint
    - npm run build-package
    - CHROME_BIN=`which chrome` NO_SANDBOX=true ENV_BROWSER=Chrome_headless npm run test
  on_success:
    - npx ci-semantic-release

resources:
    - name:             kendo-draggable-repo
      type:             gitRepo
      integration:      github-telerik
      versionTemplate:
        sourceName:       telerik/kendo-draggable
        branch:           develop
    - name: shippable-draggable-push
      type: integration
      integration: shippable-draggable
jobs:
  - name: kendo-draggable-publish_develop_as_latest
    type: runSh
    steps:
      - IN: kendo-draggable-repo
        switch: off
      - IN: kendo-draggable_ciRepo
        switch: off
      - IN: shippable-draggable-push
        switch: off
      - TASK:
          name: kendo-draggable-publish_develop
          script:
            - ssh-add $SHIPPABLEDRAGGABLEPUSH_PRIVATE_KEY_PATH
            - cd $KENDODRAGGABLEREPO_STATE && git remote set-url --push origin git@github.com:telerik/kendo-draggable.git && git checkout master && git pull --rebase
            - npm install @telerik/semantic-prerelease@1 --no-save && npx release-master
